name: API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytest requests python-dotenv jsonschema pytest-html

      - name: Create .env file
        run: |
          echo "ENV=dev" >> .env
          echo "BASE_URL=https://jsonplaceholder.typicode.com" >> .env
          echo "TIMEOUT=10" >> .env
          echo "API_KEY=mysecretkey123" >> .env

      - name: Run tests
        run: pytest -n 4 --html=reports/report.html --self-contained-html -v


